name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: cv-maxdaten-io
        attributes: pages
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --pure --run 'make pages'
    - name: Upload pages
      uses: actions/upload-artifact@v2.2.4
      with:
        name: pages
        path: build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2.0.9
      with:
        name: pages
        path: build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
