name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: cv-maxdaten-io
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
    - name: Upload pages
      uses: actions/upload-artifact@v2.2.3
      with:
        name: pages
        path: result

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2.0.9
      with:
        name: pages
        path: result
    - run: tree result/
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        build_dir: result
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
